
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.test;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-08-06T18:32:49.177+05:30
 * Generated source version: 3.3.2
 *
 */

@javax.jws.WebService(
                      serviceName = "CalServiceService",
                      portName = "CalServicePort",
                      targetNamespace = "http://test.com/",
                      wsdlLocation = "http://localhost:8567/05-CalServiceApacheCXF/services/CalServicePort?wsdl",
                      endpointInterface = "com.test.CalService")

public class CalServicePortImpl implements CalService {

    private static final Logger LOG = Logger.getLogger(CalServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.test.CalService#sub(int arg0, int arg1)*
     */
    public int sub(int arg0, int arg1) {
        LOG.info("Executing operation sub");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = -314526562;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.CalService#add(int arg0, int arg1)*
     */
    public int add(int arg0, int arg1) {
        LOG.info("Executing operation add");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            int _return = -765260011;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
