package com.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-08-06T18:32:49.197+05:30
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "CalServiceService",
                  wsdlLocation = "http://localhost:8567/05-CalServiceApacheCXF/services/CalServicePort?wsdl",
                  targetNamespace = "http://test.com/")
public class CalServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://test.com/", "CalServiceService");
    public final static QName CalServicePort = new QName("http://test.com/", "CalServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8567/05-CalServiceApacheCXF/services/CalServicePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8567/05-CalServiceApacheCXF/services/CalServicePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CalServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CalService
     */
    @WebEndpoint(name = "CalServicePort")
    public CalService getCalServicePort() {
        return super.getPort(CalServicePort, CalService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalService
     */
    @WebEndpoint(name = "CalServicePort")
    public CalService getCalServicePort(WebServiceFeature... features) {
        return super.getPort(CalServicePort, CalService.class, features);
    }

}
